src/components/App/App.js
=> added front-end branch

src/components/PeopleList/PeopleList.js, src/components/Person/Person.js, src/pages/Projects/Projects.js, src/styles/peopleList.scss
1) Fixed the double navbar and footer issue on project and person page
2) Added banner to people page with some styling tweaks
=> Feature branch

src/assets/testData.js, src/components/PeopleList/PeopleList.js, src/styles/peopleList.scss, src/styles/variables.scss
=> tweaked people page

src/appContext.js, src/components/Banner/Banner.js, src/components/Banner/index.js, src/pages/People/People.js, src/pages/Projects/Projects.js, src/pages/Publications/Publications.js, src/pages/Training/Training.js
=> added banner dynamically

src/appContext.js, src/components/Banner/Banner.js, src/pages/Home/Home.js, src/pages/People/People.js, src/pages/Projects/Projects.js, src/pages/Publications/Publications.js, src/pages/Training/Training.js
added functionality to filter contents for banner in context file.
=> added filter function to filter banner contents from static field

src/App.scss, src/appContext.js, src/assets/testData.js, src/components/App/App.js, src/pages/People/People.js, src/pages/Projects/Projects.js, src/pages/Publications/Publications.js, src/styles/publications.scss
people, publications, projects are consuming cms from now.
=> people, publications, projects consuming cms

src/App.scss, src/styles/banner.scss, src/styles/basestyle.scss, src/styles/test.scss
=> added base styles

public/index.html, src/components/Banner/Banner.js, src/styles/basestyle.scss, src/styles/typography.scss
fixed the banner, and added font family sculpin
=> fixed the banner, and added font family sculpin

package-lock.json, package.json, src/App.scss, src/assets/testData.js, src/components/App/Test.js, src/pages/Home/Announcement.js, src/pages/Home/Home.js, src/pages/Home/ProjectsCarousel.js, src/styles/announcement.scss, src/styles/home.scss, src/styles/projectsCarousel.scss
home page styled with media queries according to figma.
=> Home with mock

src/App.scss, src/components/Footer/Footer.js, src/pages/Training/Training.js, src/styles/basestyle.scss, src/styles/footer.scss, src/styles/home.scss
Also made small style changes to Home and Training.
=> modified and styled footer

src/components/NavBar/MobileNavigation.js, src/components/NavBar/Navigation.js, src/pages/Home/Home.js
now logo "DSL" clickable and will navigate home.
=> fixed h1/logo

src/appConstants.js, src/appContext.js, src/components/Profile/LeftPane.js, src/components/Profile/Profile.js, src/components/Profile/RightPane.js
changes made on appConstants, appContext, Profile components and its sub components.
=> added changes to context, profile, and right pane

src/components/NavBar/MobileNavigation.js
Now clicking on logo in mobile menu will also close the menu.
=> modified mobile nav

src/pages/Contact/Contact.js, src/styles/contact.scss
now address and map don't break on size change.
=> fixed Contact

src/styles/home.scss
Cancelled preset container height in media query at screen size 480px once the display changes to column over row
=> fixed Home Stay Updated

src/components/Header/Logo.js
fixed the home link navigation in header (mobile view)
=> fixed the home link navigation of header in mobile view

src/appContext.js, src/components/ProjectDetails/ProjectDetails.js, src/pages/Home/Home.js
-> Home page data is fixed in app Context.
=> Fixed Homepage data in app context

src/components/App/App.js, src/components/App/SharedLayout.js, src/components/ProjectDetails/ProjectDetails.js, src/components/ProjectDetails/ProjectDetailsLeft.js, src/components/ProjectDetails/ProjectDetailsNav.js, src/components/ProjectDetails/ProjectDetailsRight.js, src/pages/Projects/ProjectCard.js, src/pages/Projects/Projects.js
Fetched data from CMS for ProjectDetails component
=> fetched data from cms for project details

src/components/ProjectDetails/ProjectDetailsLeft.js, src/pages/Home/Home.js
individual sub components of project details parent component has its own data now.
=> divided components now has its own data

src/App.scss, src/components/ProjectDetails/ProjectDetails.js, src/components/ProjectDetails/ProjectDetailsLeft.js, src/components/ProjectDetails/ProjectDetailsNav.js, src/styles/ProjectsDetails.scss
added basic styling to project details navbar
=> Project details2

src/appContext.js, src/components/ProjectDetails/ProjectDetails.js, src/components/ProjectDetails/ProjectDetailsLeft.js, src/components/ProjectDetails/ProjectDetailsNav.js, src/styles/ProjectsDetails.scss
Parsed some data for Project Details component, and showcase on UI
=> showcase some data on ui

src/pages/Home/Home.js, src/styles/home.scss
Now home content is from CMS data except for Project Carousel.
Home email address and form are linked.
Fixed media queries for "Stay Updated".
=> Home - funder logo and email form

package-lock.json, package.json, src/pages/Home/Home.js, src/styles/home.scss
Fixed facebook/meta link in Contentful
Added Chakra UI loading skeleton
=> added chakra ui loading skeleton

src/pages/Home/ProjectsCarousel.js, src/styles/projectsCarousel.scss
now all project slides have gaps between them regardless of the screen size
=> gaps in project carousel

src/components/ProjectDetails/ProjectDetails.js, src/components/ProjectDetails/ProjectDetailsLeft.js, src/components/ProjectDetails/ProjectDetailsNav.js, src/components/ProjectDetails/ProjectDetailsRight.js, src/components/ProjectDetails/TeamMember.js, src/styles/ProjectsDetails.scss
Project Details component with mocks dynamic and responsive.
=> project details component now with mocks

src/appContext.js, src/components/Profile/LeftPane.js, src/components/Profile/Profile.js, src/components/Profile/ProfileNav.js, src/components/Profile/RightPane.js, src/components/ProjectDetails/ProjectDetails.js, src/components/ProjectDetails/ProjectDetailsLeft.js, src/pages/People/Person.js, src/pages/Publications/PublicationCard.js, src/pages/Publications/Publications.js, src/styles/ProjectsDetails.scss, src/styles/people.scss, src/styles/profile.scss, src/styles/projects.scss, src/styles/publications.scss
project details with mock now, and some other css fix.
=> project details with mock

src/appConstants.js, src/components/Profile/RightPane.js, src/pages/People/People.js, src/pages/Projects/Projects.js, src/pages/Publications/PublicationCard.js, src/pages/Publications/Publications.js, src/pages/Training/Training.js, src/styles/training.scss
Fixed the refreshing button on each page.
=> fixed the refreshing button problem

src/components/Profile/ProfileNav.js, src/components/ProjectDetails/ProjectDetails.js, src/pages/Publications/PublicationCard.js, src/pages/Training/Training.js
Tried to fix the default behavior of refresh button and fixed some broken links
=> fixed some broken links

src/components/Profile/RightPane.js
minor fix in  profile component.
=> fixed minor functionality in profile component

package-lock.json, package.json, src/appContext.js, src/components/Profile/LeftPane.js, src/components/Profile/RightPane.js, src/components/ProjectDetails/ProjectDetails.js, src/components/ProjectDetails/ProjectDetailsLeft.js, src/utils.js
fixed the routing from profile component to specific project.
=> fixed the routing from profile to affiliated projects

src/appConstants.js, src/appContext.js, src/components/LoadingState/LoadingState.js, src/pages/Home/Home.js, src/pages/People/People.js, src/pages/Projects/Projects.js, src/pages/Publications/Publications.js, src/pages/Training/Training.js
Implemented Loading state logic in global context, so every page is responding to loading state. 
created new component LoadingState. Here we are going to implement the Loading State.
=> implemented Loading State Logic

src/appContext.js, src/pages/Home/Home.js, src/pages/LoadingState/LoadingState.js, src/pages/People/People.js, src/pages/Projects/Projects.js, src/pages/Publications/Publications.js, src/pages/Training/Training.js, src/styles/publications.scss, src/styles/training.scss
changes made as per in morning followup
=> changes made as discussed

src/pages/Contact/Contact.js, src/pages/Home/ProjectsCarousel.js, src/styles/contact.scss, src/styles/home.scss
Added conditions to ensure all form fields in Contact are required.
Added resetForm method to clear the form after submission.
Rid of horizontal scrolls in Home and Contact for media queries.
Adjust ProjectCarousel and now at tablet size, the slides shown will be 1.
=> dsl-72, dsl-83, dsl-73

src/appContext.js, src/pages/Home/Home.js, src/pages/Training/Training.js
=> fixed the app  Training page breakage

src/pages/Home/Home.js, src/pages/Home/ProjectsCarousel.js, src/pages/Training/Training.js
fixed the banner issue from training page.
=> fixed the banner in training

src/components/Profile/RightPane.js, src/styles/profile.scss
fixed the extra space in profile component's right pane
=> fixed the extra space in Profile component right pane

src/pages/Publications/Publications.js, src/styles/publications.scss
fixed padding in publication page
=> fixed the padding issue in Publications.js

src/styles/variables.scss
=> lowered the speed of sidebar

src/styles/ProjectsDetails.scss
project-details height is fixed to not show footer
=> fixed the project details height

src/pages/People/Person.js, src/styles/people.scss
added extra space between each person in Person.js
=> added extra space between each person

src/components/ProjectDetails/ProjectDetails.js, src/components/ProjectDetails/ProjectDetailsLeft.js, src/components/ProjectDetails/ProjectDetailsNav.js, src/components/ProjectDetails/ProjectDetailsRight.js, src/pages/Projects/ProjectCard.js, src/styles/ProjectsDetails.scss, src/styles/error.scss, src/styles/profile.scss
=> fixed the css styling in projects page

src/components/Profile/RightPane.js, src/styles/profile.scss
fixed the Profile component min-height
=> fixed the Profile height
